### ISSUE TITLE
DeepL Translator

### ISSUE THREAD

**Issue by invariant** [pilotmoon/PopClip-Extensions#1005]
Ref: **[Conversation #6012](https://secure.helpscout.net/conversation/434929533/6012) / Walter**

**Comment by binaryanomaly** [comment]
That would be awesome since it is fast and really good. I have played around a bit using the html interface but there's also an undocumented json.
I have however not been able to figure out yet if there is a way to display the html output in the popclip response overlay. It does not seem to support that? It would be a nice capability since with translators the value does not come from just returning the the top hit word but rather the whole context such as: https://dict.deepl.com/english-german/search?ajax=1&query=house&source=english&onlyDictEntries=1&translator=dnsof7h3k2lgh3gda
Having that opened in a browser tab is too intrusive as it breaks the workflow on the same window in a popclip overlay would be just right.

**Comment by binaryanomaly** [comment]
I have hacked together a version using python3 and the jsonrpc api. Good enough for my personal use. I already like it much more than the Microsoft powered one. The python3 dependency does probably not make it suitable for the masses though. I can make it available if there's interest.

**Comment by invariant** [comment]
Ref: **[Conversation #6021](https://secure.helpscout.net/conversation/437696173/6021) / Tomasz**

**Comment by binaryanomaly** [comment]
My solution is available here:
https://github.com/binaryanomaly/DeepL.popclipext
if anybody is in need of a pragmatic solution before an official extension is made available.

**Comment by invariant** [comment]
Ref: **[Conversation #6303](https://secure.helpscout.net/conversation/493672360/6303) / **

**Comment by invariant** [comment]
Ref: **[Conversation #6314](https://secure.helpscout.net/conversation/496522577/6314) / Wolfgang**
