### ISSUE TITLE
iTunes Music extension not valid on macOS Catalina

### ISSUE THREAD

**Issue by wydwww** [pilotmoon/PopClip-Extensions#1112]
Due to the new Music app, the previous iTunes search is broken on macOS Catalina.

**Comment by invariant** [comment]
Conformed. I tried writing a new script but wasn;t able to access the text field control in AppleScript. Has anyone any ideas?

**Comment by wydwww** [comment]
Press `command + F` to locate the search field?

**Comment by invariant** [comment]
> Press `command + F` to locate the search field?

I think I will have to go with that. It's uglier than scripting the UI elements directly, because you can't verify whether the search field has the focus. And if the search field already has the focus then pressing ⌘F causes the "boop" sound. (And then I get emails "why is you app making an error sound?") But the show must go on.

**Comment by wydwww** [comment]
Tested with `extensions/Music.popclipextz`. If the Music app is closed, will get the boop sound.

**Comment by invariant** [comment]
Thanks. Updated with possible fix.

**Comment by invariant** [comment]
Extension released: https://pilotmoon.com/popclip/extensions/page/Music
Hopefully avoiding boop sounds now. All feedback - good/bad - welcome. Cheers.
