### ISSUE TITLE
Cannot Install Extension

### ISSUE THREAD

**Issue by bradleysawler** [pilotmoon/PopClip-Extensions#1161]
Downloaded some extensions and when I double-clicked on them I got the following error. 

Cannot Install Extension

The path /var/folders/s7/x4ygr1v909j2dlvqjtg2c77w0000gn/T/TemporaryItems/NSIRD_PopClip_0kCaBb/Underscore.popclipext does not contain a valid PopClip extension.

Reason: No such executable file: /usr/bin/php

Just recently updated macOS to: 

macOS Monterey
Version 12.0 Beta (21A5294g)

Hopefully just a Beta issue.

**Comment by invariant** [comment]
Hi, yes unfortunately Monterey does not ship with PHP. So all the PHP-based extensions will not load on Monterey. I plan to rewrite as many extensions as possible in a new language in time for final release. Beforehand I'm working on adding self-hosted JavaScript extensions, to write the replacements in (rather than jump to another scripting language, which might itself be deprecated in future).

**Comment by korm** [comment]
The extension will not install on Big Sur.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/2934341/133475285-16748f9b-4652-48d8-aeb2-c430cf279eb1.png">

**Comment by invariant** [comment]
Thanks for reporting. Can you tell me which popclip version number this is?

**Comment by korm** [comment]
Sure, build 3449

**Comment by invariant** [comment]
Thanks. Can you bump it up to 3468, released a few hours ago. I _think_ this ought to be fixed. (Un-check and check "check for updates" in the app ought to do it)

**Comment by korm** [comment]
Fixed it.  I tested it all the way through to sync via Readwise's Obsidian plugin.   Flawless.  Thanks!
