### ISSUE TITLE
I am learning to create plugins for reference and have some questions.

### ISSUE THREAD

**Issue by ixqbar** [pilotmoon/PopClip-Extensions#1229]
### _Signature.plist 

* https://github.com/pilotmoon/PopClip-Extensions/tree/master/source/OpenInBrowser.popclipext

What is the purpose of the _Signature.plist file and how is it generated?

**Comment by pilotmoon** [comment]
The signature file is generated by me using a secret cryptographic key. It tells the PopClip app that it can trust the extension and skip any warnings or restrictions it may place on unsigned extensions.

**Comment by pilotmoon** [comment]
Extensions will work fine without a signature but will show a warning on installation if they contain certain kinds of scripts. Also, PopClip will load unsigned JavaScript extensions into a separate JavaScript context instead of a shared context. This is less memory-efficient but more secure.
https://www.popclip.app/dev/#extension-signing

**Comment by ixqbar** [comment]
Thank you for your reply!

If I have completed the development of a plugin and want to share it with friends, how can I sign it to avoid warnings? Can you provide a detailed explanation of how to sign it?

**Comment by pilotmoon** [comment]
Only I can sign the extensions. If you submit a pull request to the `source-contrib` directory, I will sign it for you.

I hope soon to complete a better way of sharing and publishing extensions.

**Comment by ixqbar** [comment]
Thanks!
